sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-151.pdf --upload --lsstdoc LDM-151.tex --env=travis --ltd-product ldm-151"
env:
  global:
    # LSST the Docs credentials
    - secure: "lvUvTK7/cfmBVyhon8FklumGf0T+Fa/zT1xFmNQ5+2y6Lv8oGejUdqrSlGR+8osIwgklTydsawfnPSWcGh0FK7ATXQJkg1BRXqcznV26CN22RbwFZO4w+bEwVWVpTUhGxnl2thsINGxDrj0DZf2ic647Lw3QgViKVIeMJK56hub20A/SMLhbFqZnjmTYIrgBORHKaAOKVHMGTKHIs1pTaFhwU9EeTbhagj8kdJPZWZ16ut00h/UXrJFU8QdzjCDOLOUaz5SKrEpJOmeHgHxi2qo0/i7hvqa/4RPA5A3Lb7fEgiL93TOHTtiP+soNLHKDLddGnq5rJcVBafHabL+Jm5C6KLvGbsj9xFtp2H5v0LUU/pzgZrX8PJjCxQ+h7HdMBxgSu5hexZUoh6m1VwODYuRYhPMwVR5fJr6O6rlSgbdRGeMfAOxZmDd/mebdbx4Bi5sze914GnL9Gz23t2U/zJpGUu9MyPVKZrxpIfD4F6iCDSdi6+C6S8RtwktLpK/8VBAAmXNOKv8WA82cXTydrxwY5M0b6sbgTqOEg/cKRZCL2KY2CKuGlTDIevpqYZ6rl+EI69BTDS4qGXfG2wr7hkGGgYRffoGK7p3oIN995rxrhb+po8KJU663nr8Z8c+IOvz0wjuCGaB0KXQAj3zmjJk+W6RZhjTtSaiw/51NCxY="
    - secure: "QmYFiUEBxyJElpM62kuwrjA0gTUKaZAS6zr9TxbIdh11KwddlC7XgNMu7SaFqz7zFe16GSkaBG5LMAM2ILc8ARc3bfbM6ZORt1pXF1KaG179HlKCuUFVGnZt9Epk/89K+n5q+77rcaquOOIBeguIzk8fHyksW7O7shLYNAN1Q0gv+EaGURL/hGRJ5WNzybzkl4s3zXfaGYbGH7CIkvM62iYrClnfHMxlkHk0/NnCqLqvXhWIPpvA4EIzrl+r05E9fYufHuYwdKFDnR1LEa3lUaNw1gXOZpfKUOJpHJ32HenrjNVZyer+VG74Rp/L/d8gWTv0M8wQNFSmkMBZIf2mWCcrDpAPeKSIIudLWyT66kQ6SMR8nyA7ICY57kn8QTVCH1HC9BiafXCyU9ZCsUs6KXLQxuEbZwc550I0/JzE9ELIc0KKS5Q+w9vxcAn0CZ7ZkvcEL01CqU/PNiyGWRtQtDXx4X3oGA2+MNa231ryWEFj89Hfu+FRavW+XxJvHIG3GmVPpodYMTymf+MdMmnf+Od0ZbVGp/SORbTCLJlsBdj7q/OgRXYtv578G3mcLgPcXsmUR+Bb5YM3FnOjUK+e81c1NhCQGR12YnnNv2GkNzQkjz1Vn+ymieTwotweTjRo9wI2lgAtEEW2+Dehd/QxaI+9b+MwjZLMI68BtkozzEE="
